# Generated by Django 6.0.7 on 2026-07-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_desired_deadline_proposal_proposalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalmessage',
            name='message_type',
            field=models.CharField(choices=[('message', 'Message'), ('counter_offer', 'Counter-offer')], db_index=True, default='message', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalmessage',
            name='offer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalmessage',
            name='proposed_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proposalmessage',
            name='proposed_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalmessage',
            name='proposed_scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposalmessage',
            name='proposed_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
