# Generated by Django 6.0.7 on 2026-07-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_clientprojectrequest_projectmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='is_read_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
